//
//  ADeanColorManager.h
//  ADeanFramework
//
//  Created by lyywhg on 15/7/30.
//  Copyright (c) 2015年 ADean. All rights reserved.
//


UIKIT_EXTERN UIFont *ADeanFONT8;
UIKIT_EXTERN UIFont *ADeanFONT9;
UIKIT_EXTERN UIFont *ADeanFONT10;
UIKIT_EXTERN UIFont *ADeanFONT11;
UIKIT_EXTERN UIFont *ADeanFONT12;
UIKIT_EXTERN UIFont *ADeanFONT13;
UIKIT_EXTERN UIFont *ADeanFONT14;
UIKIT_EXTERN UIFont *ADeanFONT15;
UIKIT_EXTERN UIFont *ADeanFONT16;
UIKIT_EXTERN UIFont *ADeanFONT17;
UIKIT_EXTERN UIFont *ADeanFONT18;
UIKIT_EXTERN UIFont *ADeanFONT19;
UIKIT_EXTERN UIFont *ADeanFONT20;
UIKIT_EXTERN UIFont *ADeanFONT21;
UIKIT_EXTERN UIFont *ADeanFONT22;
UIKIT_EXTERN UIFont *ADeanFONT23;
UIKIT_EXTERN UIFont *ADeanFONT30;

UIKIT_EXTERN UIFont *ADeanBOLDFONT8;
UIKIT_EXTERN UIFont *ADeanBOLDFONT9;
UIKIT_EXTERN UIFont *ADeanBOLDFONT10;
UIKIT_EXTERN UIFont *ADeanBOLDFONT11;
UIKIT_EXTERN UIFont *ADeanBOLDFONT12;
UIKIT_EXTERN UIFont *ADeanBOLDFONT13;
UIKIT_EXTERN UIFont *ADeanBOLDFONT14;
UIKIT_EXTERN UIFont *ADeanBOLDFONT15;
UIKIT_EXTERN UIFont *ADeanBOLDFONT16;
UIKIT_EXTERN UIFont *ADeanBOLDFONT17;
UIKIT_EXTERN UIFont *ADeanBOLDFONT18;
UIKIT_EXTERN UIFont *ADeanBOLDFONT19;
UIKIT_EXTERN UIFont *ADeanBOLDFONT20;
UIKIT_EXTERN UIFont *ADeanBOLDFONT21;
UIKIT_EXTERN UIFont *ADeanBOLDFONT22;
UIKIT_EXTERN UIFont *ADeanBOLDFONT23;
UIKIT_EXTERN UIFont *ADeanBOLDFONT30;
UIKIT_EXTERN UIFont *ADeanBOLDFONT35;
UIKIT_EXTERN UIFont *ADeanBOLDFONT40;
UIKIT_EXTERN UIFont *ADeanBOLDFONT45;
UIKIT_EXTERN UIFont *ADeanBOLDFONT50;

@interface ADeanColorManager : NSObject

@end
